import type { Metadata } from 'next'
import { Inter, Geist_Mono, Archivo, IBM_Plex_Sans, IBM_Plex_Mono } from 'next/font/google'
import './globals.css'
import { Toaster } from '@/components/ui/sonner'
import { TooltipProvider } from '@/components/ui/tooltip'
import { AuthSlideOverProvider } from '@/components/auth/AuthSlideOverProvider'

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
  display: 'swap',
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
  display: 'swap',
})

// ── v5 "regimental" type system ──
const archivo = Archivo({
  variable: '--font-archivo',
  subsets: ['latin'],
  weight: ['500', '600', '700', '800', '900'],
  display: 'swap',
})

const plexSans = IBM_Plex_Sans({
  variable: '--font-plex-sans',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  display: 'swap',
})

const plexMono = IBM_Plex_Mono({
  variable: '--font-plex-mono',
  subsets: ['latin'],
  weight: ['400', '500', '600'],
  display: 'swap',
})

export const metadata: Metadata = {
  metadataBase: new URL('https://command360.co.uk'),
  title: {
    default: 'Command 360 — Interactive Command Training for UK Emergency Services',
    template: '%s | Command 360',
  },
  description:
    'Interactive command training for UK emergency services. Command 360 turns briefings, live decisions, and debriefs into structured learning — with interactive questions, AI insight, and a full record of every session.',
  keywords: [
    'command training',
    'emergency services training',
    'interactive briefings',
    'tactical decision exercises',
    'live polling',
    'incident debrief',
    'AI training insights',
  ],
  openGraph: {
    type: 'website',
    locale: 'en_GB',
    siteName: 'Command 360',
    title: 'Command 360 — Interactive Command Training for UK Emergency Services',
    description:
      'Interactive command training for UK emergency services — briefings, live decisions, and debriefs turned into structured learning with AI insight.',
    // social card image is generated by src/app/opengraph-image.tsx
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Command 360 — Interactive Command Training for UK Emergency Services',
    description:
      'Interactive command training for UK emergency services — briefings, live decisions, and debriefs turned into structured learning with AI insight.',
  },
  robots: { index: true, follow: true },
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en-GB" suppressHydrationWarning className="dark overflow-x-hidden">
      <head>
        <meta name="theme-color" media="(prefers-color-scheme: light)" content="#ffffff" />
        <meta name="theme-color" media="(prefers-color-scheme: dark)" content="#141414" />
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var m=localStorage.getItem('theme');if(m==='dark'||(!m&&window.matchMedia('(prefers-color-scheme:dark)').matches)){document.documentElement.classList.add('dark')}}catch(e){}})()`,
          }}
        />
      </head>
      <body className={`${inter.variable} ${geistMono.variable} ${archivo.variable} ${plexSans.variable} ${plexMono.variable} antialiased overflow-x-hidden`}>
        <TooltipProvider>
          <AuthSlideOverProvider>
            {children}
            <Toaster richColors position="top-right" />
          </AuthSlideOverProvider>
        </TooltipProvider>
      </body>
    </html>
  )
}
